//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsErrors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguages.RsErrors", typeof(RsErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some data with base format.
        /// </summary>
        public static string lbBadFormat {
            get {
                return ResourceManager.GetString("lbBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Autentication.
        /// </summary>
        public static string lbErrorAutentication {
            get {
                return ResourceManager.GetString("lbErrorAutentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Comunication.
        /// </summary>
        public static string lbErrorComunication {
            get {
                return ResourceManager.GetString("lbErrorComunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ErrorSaveInDataBase.
        /// </summary>
        public static string lbErrorDataBases {
            get {
                return ResourceManager.GetString("lbErrorDataBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please validate information.
        /// </summary>
        public static string lbNoInformation {
            get {
                return ResourceManager.GetString("lbNoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please validate data inexed.
        /// </summary>
        public static string lbValidData {
            get {
                return ResourceManager.GetString("lbValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please Call Administrator.
        /// </summary>
        public static string lnCallToAdmin {
            get {
                return ResourceManager.GetString("lnCallToAdmin", resourceCulture);
            }
        }
    }
}
