//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsErrors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsErrors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("lib_lenguages.rsErrors", typeof(rsErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbBadFormat {
            get {
                return ResourceManager.GetString("lbBadFormat", resourceCulture);
            }
        }
        
        public static string lbErrorAutentication {
            get {
                return ResourceManager.GetString("lbErrorAutentication", resourceCulture);
            }
        }
        
        public static string lbErrorComunication {
            get {
                return ResourceManager.GetString("lbErrorComunication", resourceCulture);
            }
        }
        
        public static string lbErrorDataBases {
            get {
                return ResourceManager.GetString("lbErrorDataBases", resourceCulture);
            }
        }
        
        public static string lbNoInformation {
            get {
                return ResourceManager.GetString("lbNoInformation", resourceCulture);
            }
        }
        
        public static string lbValidData {
            get {
                return ResourceManager.GetString("lbValidData", resourceCulture);
            }
        }
        
        public static string lnCallToAdmin {
            get {
                return ResourceManager.GetString("lnCallToAdmin", resourceCulture);
            }
        }
    }
}
