//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsMenu {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsMenu() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("lib_lenguages.RsMenu", typeof(RsMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbClean {
            get {
                return ResourceManager.GetString("lbClean", resourceCulture);
            }
        }
        
        public static string lbClose {
            get {
                return ResourceManager.GetString("lbClose", resourceCulture);
            }
        }
        
        public static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        public static string lbDeleteEntity {
            get {
                return ResourceManager.GetString("lbDeleteEntity", resourceCulture);
            }
        }
        
        public static string lbEnter {
            get {
                return ResourceManager.GetString("lbEnter", resourceCulture);
            }
        }
        
        public static string lbMessage {
            get {
                return ResourceManager.GetString("lbMessage", resourceCulture);
            }
        }
        
        public static string lbModify {
            get {
                return ResourceManager.GetString("lbModify", resourceCulture);
            }
        }
        
        public static string lbNew {
            get {
                return ResourceManager.GetString("lbNew", resourceCulture);
            }
        }
        
        public static string lbRefresh {
            get {
                return ResourceManager.GetString("lbRefresh", resourceCulture);
            }
        }
        
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        public static string lbSelect {
            get {
                return ResourceManager.GetString("lbSelect", resourceCulture);
            }
        }
        
        public static string lbUsers {
            get {
                return ResourceManager.GetString("lbUsers", resourceCulture);
            }
        }
        
        public static string lbHome {
            get {
                return ResourceManager.GetString("lbHome", resourceCulture);
            }
        }
        
        public static string lbSmokers {
            get {
                return ResourceManager.GetString("lbSmokers", resourceCulture);
            }
        }
    }
}
