//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsSmokers {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsSmokers() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("lib_lenguages.RsSmokers", typeof(RsSmokers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string clWidth {
            get {
                return ResourceManager.GetString("clWidth", resourceCulture);
            }
        }
        
        public static string clHeight {
            get {
                return ResourceManager.GetString("clHeight", resourceCulture);
            }
        }
        
        public static string clPounds {
            get {
                return ResourceManager.GetString("clPounds", resourceCulture);
            }
        }
        
        public static string clPrice_ref {
            get {
                return ResourceManager.GetString("clPrice_ref", resourceCulture);
            }
        }
        
        public static string clDetail {
            get {
                return ResourceManager.GetString("clDetail", resourceCulture);
            }
        }
        
        public static string clStock {
            get {
                return ResourceManager.GetString("clStock", resourceCulture);
            }
        }
        
        public static string lbWidth {
            get {
                return ResourceManager.GetString("lbWidth", resourceCulture);
            }
        }
        
        public static string lbHeight {
            get {
                return ResourceManager.GetString("lbHeight", resourceCulture);
            }
        }
        
        public static string lbPounds {
            get {
                return ResourceManager.GetString("lbPounds", resourceCulture);
            }
        }
        
        public static string lbPrice_ref {
            get {
                return ResourceManager.GetString("lbPrice_ref", resourceCulture);
            }
        }
        
        public static string lbDetail {
            get {
                return ResourceManager.GetString("lbDetail", resourceCulture);
            }
        }
        
        public static string lbStock {
            get {
                return ResourceManager.GetString("lbStock", resourceCulture);
            }
        }
    }
}
